name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies -- relic-toolkit
      run: |
        make -C compile

    - name: Configure CMake for abe-lsss library
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Build abe-lsss library
      run: |
        cd build
        make

    - name: Install abe-lsss library
      run: |
        cd build
        sudo make install

    - name: Test
      working-directory: build
      run: ctest -C ${{env.BUILD_TYPE}}
